export const FETCH_REF_SIDEBAR_DATA = "FETCH_REF_SIDEBAR_DATA";
export const FETCH_REF_TESTIMONAL_DATA = "FETCH_REF_TESTIMONAL_DATA";
export const FETCH_REF_SERVICES_DATA = "FETCH_REF_SERVICES_DATA";
export const FETCH_REF_ABOUT_HISTORY_DATA = "FETCH_REF_ABOUT_HISTORY_DATA";
export const FETCH_REF_ABOUT_PARISH_DATA = "FETCH_REF_ABOUT_PARISH_DATA";
export const FETCH_REF_ABOUT_TEAM_DATA = "FETCH_REF_ABOUT_TEAM_DATA";